# Generated by Django 4.0.4 on 2022-06-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictrav', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcustom',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
